export const actions = {
  FETCH_USERS: "FETCH_USERS",
  FETCH_PARTICIPANTS: "FETCH_PARTICIPANTS",
  FETCH_EMPLOYERS: "FETCH_EMPLOYERS",
  FETCH_CURRENT_USER: "FETCH_CURRENT_USER",
  DELETE_PARTICIPANT: "DELETE_PARTICIPANT",
  DELETE_EMPLOYER: "DELETE_EMPLOYER",
};

export const mutations = {
  SET_USERS: "SET_USERS",
  SET_PARTICIPANTS: "SET_PARTICIPANTS",
  SET_EMPLOYERS: "SET_EMPLOYERS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
};

export const getters = {
  GET_USERS: "GET_USERS",
  GET_PARTICIPANTS: "GET_PARTICIPANTS",
  GET_EMPLOYERS: "GET_EMPLOYERS",
  GET_CURRENT_USER: "GET_CURRENT_USER",
};
