export const actions = {
  FETCH_USERS: "FETCH_USERS",
  FETCH_PARTICIPANTS: "FETCH_PARTICIPANTS",
  FETCH_EMPLOYERS: "FETCH_EMPLOYERS",
  FETCH_CURRENT_USER: "FETCH_CURRENT_USER",
  FETCH_CURRENT_PARTICIPANT: "FETCH_CURRENT_PARTICIPANT",
  FETCH_CURRENT_EMPLOYER: "FETCH_CURRENT_EMPLOYER",
  DELETE_PARTICIPANT: "DELETE_PARTICIPANT",
  DELETE_EMPLOYER: "DELETE_EMPLOYER",
  CREATE_PARTICIPANT: "CREATE_PARTICIPANT", // Add create participant action
  UPDATE_PARTICIPANT: "UPDATE_PARTICIPANT", // Add update participant action
  CREATE_EMPLOYER: "CREATE_EMPLOYER", // Add create employer action
  UPDATE_EMPLOYER: "UPDATE_EMPLOYER", // Add update employer action
};

export const mutations = {
  SET_USERS: "SET_USERS",
  SET_PARTICIPANTS: "SET_PARTICIPANTS",
  SET_EMPLOYERS: "SET_EMPLOYERS",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_PARTICIPANT: "SET_CURRENT_PARTICIPANT",
  SET_CURRENT_EMPLOYER: "SET_CURRENT_EMPLOYER",
  ADD_PARTICIPANT: "ADD_PARTICIPANT", // Change from SET to ADD for consistency
  UPDATE_PARTICIPANT: "UPDATE_PARTICIPANT", // Add update participant mutation
  ADD_EMPLOYER: "ADD_EMPLOYER", // Change from SET to ADD for consistency
  UPDATE_EMPLOYER: "UPDATE_EMPLOYER", // Add update employer mutation
};

export const getters = {
  GET_USERS: "GET_USERS",
  GET_PARTICIPANTS: "GET_PARTICIPANTS",
  GET_EMPLOYERS: "GET_EMPLOYERS",
  GET_CURRENT_USER: "GET_CURRENT_USER",
  GET_CURRENT_PARTICIPANT: "GET_CURRENT_PARTICIPANT",
  GET_CURRENT_EMPLOYER: "GET_CURRENT_EMPLOYER",
};
